"""empty message

Revision ID: 3c9963c9949c
Revises: df5e129bb317
Create Date: 2022-03-28 05:14:15.114940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c9963c9949c'
down_revision = 'df5e129bb317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admincommands', sa.Column('date_added', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admincommands', 'date_added')
    # ### end Alembic commands ###
