"""empty message

Revision ID: 66313c65e0e1
Revises: 
Create Date: 2022-04-19 21:16:52.769130

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66313c65e0e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_contracts', sa.Column('commute_pay', sa.Float(), nullable=True))
    op.add_column('campaigns', sa.Column('default_commute_pay', sa.Float(), nullable=False))
    op.drop_column('campaigns', 'commute_pay')
    op.add_column('paystamps', sa.Column('activity', sa.String(length=500), nullable=True))
    op.add_column('paystamps', sa.Column('note', sa.String(length=500), nullable=True))
    op.drop_constraint('paystamps_ibfk_3', 'paystamps', type_='foreignkey')
    op.create_foreign_key(None, 'paystamps', 'activities', ['activity'], ['activity'])
    op.drop_column('paystamps', 'activity_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paystamps', sa.Column('activity_id', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'paystamps', type_='foreignkey')
    op.create_foreign_key('paystamps_ibfk_3', 'paystamps', 'activities', ['activity_id'], ['activity'])
    op.drop_column('paystamps', 'note')
    op.drop_column('paystamps', 'activity')
    op.add_column('campaigns', sa.Column('commute_pay', mysql.FLOAT(), nullable=False))
    op.drop_column('campaigns', 'default_commute_pay')
    op.drop_column('campaign_contracts', 'commute_pay')
    # ### end Alembic commands ###
