"""empty message

Revision ID: 708a334d09c1
Revises: 66313c65e0e1
Create Date: 2022-04-19 21:22:25.943380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '708a334d09c1'
down_revision = '66313c65e0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_contracts', sa.Column('pay_out', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_contracts', 'pay_out')
    # ### end Alembic commands ###
