"""empty message

Revision ID: 9e3b19a95a16
Revises: 708a334d09c1
Create Date: 2022-04-22 12:58:44.355695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e3b19a95a16'
down_revision = '708a334d09c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paystamps', sa.Column('activity_id', sa.String(length=500), nullable=True))
    op.drop_constraint('paystamps_ibfk_3', 'paystamps', type_='foreignkey')
    op.create_foreign_key(None, 'paystamps', 'activities', ['activity_id'], ['activity'])
    op.drop_column('paystamps', 'activity')
    op.add_column('receipts', sa.Column('accepted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'accepted')
    op.add_column('paystamps', sa.Column('activity', mysql.VARCHAR(length=500), nullable=True))
    op.drop_constraint(None, 'paystamps', type_='foreignkey')
    op.create_foreign_key('paystamps_ibfk_3', 'paystamps', 'activities', ['activity'], ['activity'])
    op.drop_column('paystamps', 'activity_id')
    # ### end Alembic commands ###
