"""initial

Revision ID: df5e129bb317
Revises: 
Create Date: 2022-03-27 05:09:29.514261

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df5e129bb317'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shiftstamps', 'campaign_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shiftstamps', 'campaign_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
